name = "rxh/main"

[[server]]
listen = ["192.168.100.7:9000"]

[[forward]]
algorithm = "WRR"

[[backends]]
backends = [{ address = "127.0.0.1:3000", weight = 1 }]

matchs = [
    { uri = "/", forward = ["127.0.0.1:8080", "127.0.0.1:8000"] },
    { uri = "/", serve = "/Users/andrescuello/Documents/GitHub/AndresCuello7/Systems/rxh" },
]